Block Editor: Resolve styling differences
siteorigin/settings pull request #70
Opened 2021-04-04 15:42 UTC by AlexGStapleton

Resolve https://github.com/siteorigin/settings/issues/54

2021-04-05 09:32 UTC, Misplon commented on inc/page_settings.php
> +			array( ),
Should this rather be `array(),` ?

2021-04-05 09:32 UTC, Misplon requested changes
Minor spacing query otherwise looks good.

2021-04-05 16:27 UTC, Misplon approved these changes

2021-04-06 13:03 UTC, gregpriday approved these changes

2021-04-06 13:04 UTC, merged